# Generated by Django 5.2 on 2025-05-24 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skyfinance_app', '0004_balance_transactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='memo',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
