# Generated by Django 5.2 on 2025-05-24 15:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skyfinance_app', '0005_alter_transactions_memo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='transaction_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
