# Generated by Django 5.2 on 2025-05-25 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skyfinance_app', '0007_alter_balance_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
