# Generated by Django 5.2 on 2025-05-25 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skyfinance_app', '0008_alter_balance_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='category',
            field=models.CharField(choices=[('rent', 'Rent'), ('utilities', 'Utilities'), ('food', 'Food'), ('groceries', 'Groceries'), ('entertainment', 'Entertainment'), ('misc', 'Miscellaneous')], max_length=255, null=True),
        ),
    ]
