# Generated by Django 5.2 on 2025-05-27 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skyfinance_app', '0010_alter_transactions_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='memo',
            field=models.TextField(blank=True, max_length=50),
        ),
    ]
