# Generated by Django 5.2 on 2025-05-27 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skyfinance_app', '0011_alter_transactions_memo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='memo',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
